config/routes.rb
Rails.application.routes.draw do
  resource :session
  resources :users
  resources :records
  resources :unhealthy_thought_types
  resources :healthy_thought_types

  root 'sessions#new'
  get 'signup' => 'users#new'
  get 'signin' => 'sessions#new'

end

app/models/record.rb
class Record < ActiveRecord::Base
  belongs_to :unhealthy_thought_type
  belongs_to :healthy_thought_type
  belongs_to :user

  validates :date, :event, :thought_about_event, :feeling_about_thought, :unhealthy_action, :unhealthy_thought_type_id, :healthy_thought_type_id, :reframe_statement, :healthy_action, presence: true


  #method to list top five most used negative thought types and get their name and  provide a usage count
  def self.unhealthy_thought_type_counter
     # used_unhealthy_thought_types_query = "SELECT unhealthy_thought_types.name AS unhealthy_thought, COUNT(*) FROM records r, LEFT JOIN unhealthy_thought_types u ON unhealthy_thought_types.id = records.unhealthy_thought_type_id GROUP BY unhealthy_thought LIMIT '5'"
# used_unhealthy_thought_types_query
  $zorro = 1
    Record.find_by_sql(["
      SELECT r.unhealthy_thought_type_id, t.name
      FROM records r
      JOIN unhealthy_thought_types t ON t.id = r.unhealthy_thought_type_id
      JOIN users u ON u.id = r.user_id
      WHERE r.user_id = $zorro
      GROUP BY r.unhealthy_thought_type_id, t.name
      "])

  end #thought_type_counter

  # def counter(record_id)
  #   jbjkhf 
  # end #counter(record_id)

end

# Record.find_by_sql(["SELECT * FROM (#{used_unhealthy_thought_types_query}) as all_unhealthy_thought_types"])
# SELECT unhealthy_thought_types.name AS unhealthy_thought, COUNT(*) FROM records r,
# LEFT JOIN unhealthy_thought_types u ON unhealthy_thought_types.id = records.unhealthy_thought_type_id
# GROUP BY unhealthy_thought;

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :set_record, only: [:show, :edit, :update, :destroy]
  before_action :correct_user_record, only: [:show, :edit, :update]

  # GET /records
  # GET /records.json
  def index
    @records = Record.where(user_id: current_user.id).order(date: 'desc')
    # @experienced_unhealthy_thought_types = @records.unhealthy_thought_type_counter
  end

  # GET /records/1
  # GET /records/1.json
  def show
  end

  # GET /records/new
  def new
    @record = Record.new
  end

  # GET /records/1/edit
  def edit
  end

  # POST /records
  # POST /records.json
  def create
    @record = Record.new(record_params)
    @record.user_id = current_user.id

    respond_to do |format|
      if @record.save
        format.html { redirect_to @record, notice: 'Record was successfully created.' }
        format.json { render :show, status: :created, location: @record }
      else
        format.html { render :new }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /records/1
  # PATCH/PUT /records/1.json
  def update
    respond_to do |format|
      if @record.update(record_params)
        format.html { redirect_to @record, notice: 'Record was successfully updated.' }
        format.json { render :show, status: :ok, location: @record }
      else
        format.html { render :edit }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /records/1
  # DELETE /records/1.json
  def destroy
    @record.destroy
    respond_to do |format|
      format.html { redirect_to records_url, notice: 'Record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_record
      @record = Record.find(params[:id])
    end

    def correct_user_record
      unless (current_user_admin?) || (current_user.records.include? @record)
        redirect_to records_url, notice: "Whoops! That wasn't your record."
      end #if
    end #correct_user_record

    # Never trust parameters from the scary internet, only allow the white list through.
    def record_params
      params.require(:record).permit(:date, :event, :thought_about_event, :feeling_about_thought, :unhealthy_action, :unhealthy_thought_type_id, :healthy_thought_type_id, :reframe_statement, :healthy_action, :star, :user_id)
    end
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/records/_form.html.erb
<%= form_for(@record) do |f| %>
  <% if @record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@record.errors.count, "error") %> prohibited this record from being saved:</h2>

      <ul>
      <% @record.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :event %><br>
    Describe the event that triggered your feelings.<br>
    <%= f.text_area :event %>
  </div>
  <div class="field">
    <%= f.label :thought_about_event %><br>
    What did you think about this event?</br>
    <%= f.text_area :thought_about_event %>
  </div>
  <div class="field">
    <%= f.label :feeling_about_thought %><br>
    What feelings were triggered by that thought?<br>
    <%= f.text_area :feeling_about_thought %>
  </div>
  <div class="field">
    <%= f.label :unhealthy_action %><br>
    What actions did these feelings inspire you to take?<br>
    <%= f.text_area :unhealthy_action %>
  </div>
  <div class="field">
    <%= f.label :unhealthy_thought_type %><br>
    Which of these usual storylines best fits this situation?<br>
    <%= f.collection_select :unhealthy_thought_type_id, UnhealthyThoughtType.all, :id, :thought_type_dropdown_display_name, { :prompt => '-- Select --' } %>
  </div>
  <div class="field">
    <%= f.label :healthy_thought_type %><br>
    Which healthy thought type is more appropriate for this situation?<br>
    <%= f.collection_select :healthy_thought_type_id, HealthyThoughtType.all, :id, :thought_type_dropdown_display_name, { :prompt => '-- Select --' } %>
  </div>
  <div class="field">
    <%= f.label :reframe_statement %><br>
    Using your healthy thought type, write a more accurate statement describing the situation.<br>
    <%= f.text_area :reframe_statement %>
  </div>
  <div class="field">
    <%= f.label :healthy_action %><br>
    What actions does this new statement inspire you to make?<br>
    <%= f.text_area :healthy_action %>
  </div>
  <div class="field">
    <%= f.label :star %><br>
    <%= f.check_box :star %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/records/_progressbar.erb
<div class="progressbar">
  <div class="progress-block"></div>
</div>

app/views/records/edit.html.erb
<h1>Editing Record</h1>

<%= render 'form' %>

<%= link_to 'Show', @record %> |
<%= link_to 'Back', records_path %>

app/views/records/index.html.erb
<p id="notice"><%= notice %></p>

<div class="welcome">
   <h1>Welcome back <%= @current_user.name %></h1>
   <div class="bottom-buttons">
    <div class="button"><%= link_to 'New Record', new_record_path %></div>
    <div style="clear:both"></div>
  </div> <!-- bottom-buttons -->
</div> <!-- welcome -->

<% @records.each do |record| %>
<article class="index">
  <div class="box-link">
  <%= link_to image_tag("link.png"), record %>
  </div>
  <h1><%= record.unhealthy_thought_type.name %> <i class="fa fa-arrow-right"></i> <%= record.healthy_thought_type.name %>
    <% if record.star.present? %>
      <sup><i class="fa fa-star"></i></sup>
    <% end %>
  </h1>
  <p>
    <strong>From:</strong> <%= record.event %><br>
    <strong>To:</strong> <%= record.reframe_statement %><br>
    <span class="timestamp"><%= time_ago_in_words(record.date) %> ago</span></br>
  </p>
</article>
<% end %>


<hr>
<div style="background-color: beige; width: 30%;">
  <h3>Most Frequently Expereinced Thought Types</h3>
  <p>
  <% if @experienced_unhealthy_thought_types == nil %>
  sql not working
  <% else %>
  <ol>
    <% @experienced_unhealthy_thought_types.each do |eutt| %>
    <li><%= eutt.name %></li>
    <% end %>
  </ol>
  <% end %>
  </p>
</div>

app/views/records/new.html.erb
<h1>New Record</h1>

<%= form_for(@record) do |f| %>
  <%= render 'shared/errors', object: @record %>

  <div id="step1">
    <p>Step 1 of 6</p>
    <%= render 'progressbar' %>
    <div class="field">
      <%= f.label :event %>*<br>
      Describe the event that triggered your feelings.<br>
      <%= f.text_area :event, class: "form-control", required: true %>
    </div>

    <div class="field">
      <%= f.label :date %>*<br>
      <%= f.date_field :date, class: "form-control" %>
    </div>
    <div class="bottom-buttons">
      <p class="button back"><%= link_to "Cancel", records_path %></p>
      <p class="step2-link button next"><%= link_to "Next", "#step2" %></p>
      <div style="clear:both"></div>
    </div> <!-- bottom-buttons -->
  </div> <!-- step1 -->

  <div id="step2" class="step">
    <p>Step 2 of 6</p>
    <%= render 'progressbar' %>
    <div class="field">
      <%= f.label :thought_about_event %>*<br>
      What did you think about this event?</br>
      <%= f.text_area :thought_about_event, class: "form-control" %>
    </div>

    <div class="field">
      <%= f.label :unhealthy_thought_type %>*<br>
      Which of these thought types does that sound like?<br>
      <%= f.collection_select :unhealthy_thought_type_id, UnhealthyThoughtType.all, :id, :thought_type_dropdown_display_name, { :prompt => '-- Select --' }, class: "form-control" %>
    </div>
    <div class="bottom-buttons">
      <p class="step1-link button back"><%= link_to "Back", "#step1" %></p>
      <p class="step3-link button next"><%= link_to "Next", "#step3" %></p>
      <div style="clear:both"></div>
    </div> <!-- bottom-buttons -->
  </div><!-- step2 -->

  <div id="step3" class="step">
    <p>Step 3 of 6</p>
    <%= render 'progressbar' %>
    <div class="field">
      <%= f.label :feeling_about_thought %>*<br>
      What feelings were triggered by that thought?<br>
      <%= f.text_area :feeling_about_thought, class: "form-control" %>
    </div>
    <div class="bottom-buttons">
      <p class="step2-link button back"><%= link_to "Back", "#step2" %></p>
      <p class="step4-link button next"><%= link_to "Next", "#step4" %></p>
      <div style="clear:both"></div>
    </div> <!-- bottom-buttons -->
  </div><!-- step3 -->

  <div id="step4" class="step">
    <p>Step 4 of 6</p>
    <%= render 'progressbar' %>
    <div class="field">
      <%= f.label :unhealthy_action %>*<br>
      What actions did these feelings inspire you to take?<br>
      <%= f.text_area :unhealthy_action, class: "form-control" %>
    </div>
    <div class="bottom-buttons">
      <p class="step3-link button back"><%= link_to "Back", "#step3" %></p>
      <p class="step5-link button next"><%= link_to "Next", "#step5" %></p>
      <div style="clear:both"></div>
    </div> <!-- bottom-buttons -->
  </div><!-- step4 -->

  <div id="step5" class="step">
    <p>Step 5 of 6</p>
    <%= render 'progressbar' %>
    <div class="field">
      <%= f.label :healthy_thought_type %>*<br>
      Which healthy thought type is more appropriate for this situation?<br>
      <%= f.collection_select :healthy_thought_type_id, HealthyThoughtType.all, :id, :thought_type_dropdown_display_name, { :prompt => '-- Select --' }, class: "form-control" %>
    </div>
    <div class="field">
      <%= f.label :reframe_statement %>*<br>
      With your healthy thought type in mind, write a more accurate statement describing the situation.<br>
      <%= f.text_area :reframe_statement, class: "form-control" %>
    </div>
    <div class="bottom-buttons">
      <p class="step4-link button back"><%= link_to "Back", "#step4" %></p>
      <p class="step6-link button next"><%= link_to "Next", "#step6" %></p>
      <div style="clear:both"></div>
    </div> <!-- bottom-buttons -->
  </div><!-- step5 -->

  <div id="step6" class="step">
    <p>Step 6 of 6</p>
    <%= render 'progressbar' %>
    <div class="field">
      <%= f.label :healthy_action %>*<br>
      What actions does this new statement inspire you to make?<br>
      <%= f.text_area :healthy_action, class: "form-control" %>
    </div>
    <div class="bottom-buttons">
      <p class="step5-link button back"><%= link_to "Back", "#step5" %></p>
      <p class="actions"><%= f.submit "Finish & Save", :class=> "button" %></p>
      <div style="clear:both"></div>
    </div> <!-- bottom-buttons -->
  </div><!-- step6 -->

<% end %><!-- end form for -->


<div class="button back"><%= link_to "Cancel", records_path %></div>

app/views/records/show.html.erb
<article class="show">

  <p id="notice"><%= notice %></p>
  <p>Remapping Record Details -- USER: <%= @record.user.name %></p>
  <h1><%= @record.unhealthy_thought_type.name %> <i class="fa fa-arrow-right"></i> <%= @record.healthy_thought_type.name %>
    <% if @record.star.present? %>
      <sup><i class="fa fa-star"></i></sup>
    <% end %>
  </h1>

  <p><%= @record.date %></p>

  <h2>Trigger Event:</h2>
  <p><%= @record.event %></p>

  <h2>Thought About the Event:</h2>
  <p><%= @record.thought_about_event %></p>

    <h2>Feeling about thought:</h2>
    <p><%= @record.feeling_about_thought %></p>

    <h2>Unhealthy action:</h2>
    <p><%= @record.unhealthy_action %></p>

    <h2>Unhealthy thought type:</h2>
    <p><%= @record.unhealthy_thought_type.name %> (<%= @record.unhealthy_thought_type.explanation %>)</p>

    <h2>Healthy Thought Type:</h2>
    <p><%= @record.healthy_thought_type.name %> (<%= @record.healthy_thought_type.explanation %>)</p>

    <h2>Reframe Statement:</h2>
    <p><%= @record.reframe_statement %></p>

    <h2>Healthy action:</h2>
    <p><%= @record.healthy_action %></p>

</article>

<%= link_to 'Edit', edit_record_path(@record) %> |
<%= link_to 'Destroy', @record, method: :delete, data: { confirm: 'Are you sure you want to delete this record? This cannot be undone.' } %> |
<%= link_to 'Back', records_path %>