config/routes.rb
Rails.application.routes.draw do
  resource :session
  resources :users
  resources :records
  resources :unhealthy_thought_types
  resources :healthy_thought_types

  root 'sessions#new'
  get 'signup' => 'users#new'
  get 'signin' => 'sessions#new'

end

app/controllers/unhealthy_thought_types_controller.rb
class UnhealthyThoughtTypesController < ApplicationController
  before_action :set_unhealthy_thought_type, only: [:show, :edit, :update, :destroy]

  # GET /unhealthy_thought_types
  # GET /unhealthy_thought_types.json
  def index
    @unhealthy_thought_types = UnhealthyThoughtType.all.order(name: 'asc')
  end

  # GET /unhealthy_thought_types/1
  # GET /unhealthy_thought_types/1.json
  def show
  end

  # GET /unhealthy_thought_types/new
  def new
    @unhealthy_thought_type = UnhealthyThoughtType.new
  end

  # GET /unhealthy_thought_types/1/edit
  def edit
  end

  # POST /unhealthy_thought_types
  # POST /unhealthy_thought_types.json
  def create
    @unhealthy_thought_type = UnhealthyThoughtType.new(unhealthy_thought_type_params)

    respond_to do |format|
      if @unhealthy_thought_type.save
        format.html { redirect_to @unhealthy_thought_type, notice: 'Unhealthy thought type was successfully created.' }
        format.json { render :show, status: :created, location: @unhealthy_thought_type }
      else
        format.html { render :new }
        format.json { render json: @unhealthy_thought_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /unhealthy_thought_types/1
  # PATCH/PUT /unhealthy_thought_types/1.json
  def update
    respond_to do |format|
      if @unhealthy_thought_type.update(unhealthy_thought_type_params)
        format.html { redirect_to @unhealthy_thought_type, notice: 'Unhealthy thought type was successfully updated.' }
        format.json { render :show, status: :ok, location: @unhealthy_thought_type }
      else
        format.html { render :edit }
        format.json { render json: @unhealthy_thought_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /unhealthy_thought_types/1
  # DELETE /unhealthy_thought_types/1.json
  def destroy
    @unhealthy_thought_type.destroy
    respond_to do |format|
      format.html { redirect_to unhealthy_thought_types_url, notice: 'Unhealthy thought type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_unhealthy_thought_type
      @unhealthy_thought_type = UnhealthyThoughtType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def unhealthy_thought_type_params
      params.require(:unhealthy_thought_type).permit(:name, :explanation, :example)
    end
end

app/helpers/unhealthy_thought_types_helper.rb
module UnhealthyThoughtTypesHelper
end

app/views/unhealthy_thought_types/_form.html.erb
<%= form_for(@unhealthy_thought_type) do |f| %>
  <% if @unhealthy_thought_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@unhealthy_thought_type.errors.count, "error") %> prohibited this unhealthy_thought_type from being saved:</h2>

      <ul>
      <% @unhealthy_thought_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :explanation %><br>
    <%= f.text_field :explanation %>
  </div>
  <div class="field">
    <%= f.label :example %><br>
    <%= f.text_area :example %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/unhealthy_thought_types/edit.html.erb
<h1>Editing Unhealthy Thought Type</h1>

<%= render 'form' %>

<%= link_to 'Show', @unhealthy_thought_type %> |
<%= link_to 'Back', unhealthy_thought_types_path %>

app/views/unhealthy_thought_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Manage Unhealthy Thought Types</h1>

<%= link_to '+ Create New', new_unhealthy_thought_type_path %>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Explanation</th>
      <th>Example</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @unhealthy_thought_types.each do |unhealthy_thought_type| %>
      <tr>
        <td><%= link_to unhealthy_thought_type.name, edit_unhealthy_thought_type_path(unhealthy_thought_type) %></td>
        <td><%= unhealthy_thought_type.explanation %></td>
        <td><%= unhealthy_thought_type.example %></td>
        <td><%= link_to 'Edit', edit_unhealthy_thought_type_path(unhealthy_thought_type) %></td>
        <td><%= link_to 'Delete', unhealthy_thought_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/unhealthy_thought_types/new.html.erb
<h1>New Unhealthy Thought Type</h1>

<%= render 'form' %>

<%= link_to 'Back', unhealthy_thought_types_path %>

app/views/unhealthy_thought_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @unhealthy_thought_type.name %>
</p>

<p>
  <strong>Explanation:</strong>
  <%= @unhealthy_thought_type.explanation %>
</p>

<p>
  <strong>Example:</strong>
  <%= @unhealthy_thought_type.example %>
</p>

<%= link_to 'Edit', edit_unhealthy_thought_type_path(@unhealthy_thought_type) %> |
<%= link_to 'Back', unhealthy_thought_types_path %>