config/routes.rb
Rails.application.routes.draw do
  resource :session
  resources :users
  resources :records
  resources :unhealthy_thought_types
  resources :healthy_thought_types

  root 'sessions#new'
  get 'signup' => 'users#new'
  get 'signin' => 'sessions#new'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cognitive2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href="https://fonts.googleapis.com/css?family=Alegreya+Sans|Josefin+Sans|Montserrat" rel="stylesheet">
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

  <!-- FontAwesome -->
  <script src="https://use.fontawesome.com/394d681b20.js"></script>
  <%= csrf_meta_tags %>
</head>
<body class="body">
<div class="wrapper">
  <nav>
    <%= link_to "Records", records_path %>
    <% if current_user_admin? %>
    | <%= link_to "Users", users_path %> | <%= link_to "Healthy", healthy_thought_types_path %> | <%= link_to "Unhealthy", unhealthy_thought_types_path %>
    <% end %>
    <% if current_user %>
      | User: <%= link_to current_user.name, current_user %> (id <%= current_user.id %>) | <%= link_to "Edit Account", edit_user_path(current_user) %> | <%= link_to 'Sign Out', session_path, method: :delete, class: 'button' %>

    <% else %>
      <%= link_to "Sign In", new_session_path %> | <%= link_to "Sign Up", signup_path %>
    <% end %>
  </nav>

  <%= yield %>

  <%#= debug(params) if Rails.env.development? %>

</div> <!-- container -->

</body>
</html>